plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/dinky@v0.2.0
title: IT3100
description: System Administration 
show_downloads: false
relative_links:
  enabled: true
  collections: true
