plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/dinky@v0.2.0
title: DTS Internship workshop
description: The fall 2023 workshop for potential interns
show_downloads: false
relative_links:
  enabled: true
  collections: true
